// Struct field layout recovery for FA.EXE known base-pointer types.
// For each known struct type, scans all instructions in FA.EXE for
// register-indirect memory accesses at known offsets, then groups results
// by offset to produce a struct skeleton (offset, access count, accessor names).
//
// Known types covered:
//   entity   -- general game object base (broad 0x00-0x11E)
//   PROJ_TYPE -- missile/projectile extension (0x50-0x7F)
//   PT_TYPE  -- aircraft performance type (0x00-0xC0)
//   CN_INFO  -- network config struct (0x00-0x200)
//   GV_TYPE  -- ground vehicle extension (0x00-0x80)
//   OT_TYPE  -- ordnance type (0x00-0x60)
//   NT_TYPE  -- nav target type (0x00-0x60)
//
// Invoke: run_ghidra.bat RecoverStructs.java
// Output: %FA_PROJECT%\output\RecoverStructs.txt

import ghidra.app.script.GhidraScript;
import ghidra.program.model.address.*;
import ghidra.program.model.listing.*;
import ghidra.program.model.scalar.Scalar;
import ghidra.program.model.symbol.*;
import java.io.*;
import java.util.*;

public class RecoverStructs extends GhidraScript {

    private PrintWriter out;

    @Override
    public void run() throws Exception {
        String projectDir = System.getenv("FA_PROJECT");
        if (projectDir == null || projectDir.isEmpty())
            projectDir = System.getProperty("java.io.tmpdir");
        File outDir = new File(projectDir, "output");
        outDir.mkdirs();
        File outFile = new File(outDir, "RecoverStructs.txt");
        out = new PrintWriter(new FileWriter(outFile));

        out.println("// RecoverStructs -- FA.EXE struct field access maps");
        out.println("// Scan range: 0x400000-0x540000");
        out.println("// Generated by RecoverStructs.java\n");

        // entity base: broad offset scan covering all known entity fields
        recoverStruct("entity", 0x00400000L, 0x00540000L, 0x00, 0x11E);

        // PROJ_TYPE: missile extension fields (entity base + 0x50)
        recoverStruct("PROJ_TYPE (extension 0x50-0x7F)", 0x004c0000L, 0x004c3000L, 0x50, 0x7F);

        // PT_TYPE: aircraft performance type
        recoverStruct("PT_TYPE (perf type 0x00-0xC0)", 0x00400000L, 0x00540000L, 0x00, 0xC0);

        // CN_INFO: multiplayer network config
        recoverStruct("CN_INFO (net config 0x00-0x200)", 0x00400000L, 0x00540000L, 0x00, 0x200);

        // GV_TYPE: ground vehicle extension
        recoverStruct("GV_TYPE (ground vehicle 0x00-0x80)", 0x00470000L, 0x00480000L, 0x00, 0x80);

        // OT_TYPE: ordnance type
        recoverStruct("OT_TYPE (ordnance type 0x00-0x60)", 0x00400000L, 0x00540000L, 0x00, 0x60);

        // NT_TYPE: nav target type
        recoverStruct("NT_TYPE (nav target 0x00-0x60)", 0x00400000L, 0x00540000L, 0x00, 0x60);

        out.close();
        println("RecoverStructs complete -> " + outFile.getAbsolutePath());
    }

    private void recoverStruct(String label, long scanStart, long scanEnd,
                                int minOff, int maxOff) throws Exception {
        out.println("\n// ============================================================");
        out.println("// STRUCT: " + label);
        out.println("// Scan: 0x" + Long.toHexString(scanStart)
                + " - 0x" + Long.toHexString(scanEnd)
                + "  offsets 0x" + Integer.toHexString(minOff)
                + " - 0x" + Integer.toHexString(maxOff));
        out.println("// ============================================================");

        // offset -> list of accessor function names
        Map<Integer, List<String>> accessors = new TreeMap<>();

        AddressSpace space = currentProgram.getAddressFactory().getDefaultAddressSpace();
        Listing listing = currentProgram.getListing();
        FunctionManager fm = currentProgram.getFunctionManager();
        Address endAddr = space.getAddress(scanEnd);

        InstructionIterator instrs = listing.getInstructions(space.getAddress(scanStart), true);
        while (instrs.hasNext()) {
            Instruction instr = instrs.next();
            if (instr.getAddress().compareTo(endAddr) > 0) break;
            for (int i = 0; i < instr.getNumOperands(); i++) {
                for (Object obj : instr.getOpObjects(i)) {
                    if (obj instanceof Scalar) {
                        long val = ((Scalar) obj).getUnsignedValue();
                        if (val >= minOff && val <= maxOff) {
                            int off = (int) val;
                            Function fn = fm.getFunctionContaining(instr.getAddress());
                            String fnName = fn != null ? fn.getName() : "?";
                            accessors.computeIfAbsent(off, k -> new ArrayList<>()).add(fnName);
                        }
                    }
                }
            }
        }

        if (accessors.isEmpty()) {
            out.println("// (no accesses found in range)");
            return;
        }

        out.println("// offset | count | accessors (first 5)");
        for (Map.Entry<Integer, List<String>> e : accessors.entrySet()) {
            int off = e.getKey();
            List<String> fns = e.getValue();
            // deduplicate
            Set<String> unique = new LinkedHashSet<>(fns);
            List<String> sample = new ArrayList<>(unique);
            if (sample.size() > 5) sample = sample.subList(0, 5);
            out.println("  0x" + String.format("%02X", off)
                    + "  (" + fns.size() + "x)  "
                    + String.join(", ", sample));
        }
        out.println("// Total distinct offsets: " + accessors.size());
    }
}
